import fs from 'fs';
import path from 'path';

const photoTemplates = [
  {
    id: 'black-luxury-portrait',
    type: 'photo',
    name: 'Black Luxury Portrait',
    category: 'royal',
    subCategory: 'Luxury & Rich Look',
    gender: 'male',
    description: 'Jet black silk background with rim lighting, tailored bespoke black tuxedo, and subtle golden highlights.',
    badge: '👑 Billionaire',
    creditCost: 50,
    featured: true,
    sortPriority: 1,
    isActive: true,
    prompt: 'Ultra-luxury black portrait photography, tailored jet black designer tuxedo, subtle warm gold rim light, cinematic studio bokeh',
    beforeFile: 'src/assets/images/aarav_before_1790227490151.jpg',
    afterFile: 'src/assets/images/aarav_noir_after_1790227515442.jpg',
    likesCount: 38400,
    tags: ['luxury', 'black suit', 'rich look', 'boys', 'men', 'gold lighting'],
  },
  {
    id: 'billionaire-office-look',
    type: 'photo',
    name: 'Billionaire Office Look',
    category: 'professional',
    subCategory: 'Professional & Career',
    gender: 'male',
    description: 'High-rise executive corner office overlooking glass skyscrapers with charcoal pin-striped suit and luxury watch.',
    badge: '💼 Forbes Cover',
    creditCost: 50,
    featured: false,
    sortPriority: 2,
    isActive: true,
    prompt: 'Billionaire CEO executive portrait, bespoke charcoal tailored pinstripe suit, floor-to-ceiling Manhattan financial view, power stance',
    beforeFile: 'src/assets/images/aarav_before_1790227490151.jpg',
    afterFile: 'src/assets/images/aarav_exec_after_1790227502899.jpg',
    likesCount: 29800,
    tags: ['billionaire', 'office', 'ceo', 'suit', 'professional', 'men'],
  },
  {
    id: 'royal-indian-portrait',
    type: 'photo',
    name: 'Royal Indian Darbar',
    category: 'royal',
    subCategory: 'Indian & Desi',
    gender: 'male',
    description: 'Grand royal palace court with antique sandstone arches, royal silk achkan, and majestic Rajput aura.',
    badge: '👑 Royal Darbar',
    creditCost: 50,
    featured: true,
    sortPriority: 3,
    isActive: true,
    prompt: 'Majestic Rajput royal king portrait in Udaipur palace courtyard, antique carved sandstone, handcrafted silk sherwani, uncut polki jewelry',
    beforeFile: 'src/assets/images/aarav_before_1790227490151.jpg',
    afterFile: 'src/assets/images/aarav_royal_after_1790227528118.jpg',
    likesCount: 57800,
    tags: ['royal', 'indian', 'desi', 'sherwani', 'rajasthani', 'palace'],
  },
  {
    id: 'penthouse-night-portrait',
    type: 'photo',
    name: 'Penthouse Night Portrait',
    category: 'creative',
    subCategory: 'Luxury & Rich Look',
    gender: 'male',
    description: 'Private penthouse balcony overlooking an illuminated neon cityscape at midnight with designer casual blazer.',
    badge: '🌃 Penthouse',
    creditCost: 50,
    featured: false,
    sortPriority: 4,
    isActive: true,
    prompt: 'Ultra-luxury penthouse balcony portrait at midnight, panoramic glass city skyline, warm architectural lighting, bespoke turtleneck',
    beforeFile: 'src/assets/images/aarav_before_1790227490151.jpg',
    afterFile: 'src/assets/images/aarav_penthouse_after_1790227608456.jpg',
    likesCount: 46200,
    tags: ['penthouse', 'night', 'balcony', 'cityscape', 'boys'],
  },
  {
    id: 'royal-rajputana-princess',
    type: 'photo',
    name: 'Royal Rajputana Princess',
    category: 'royal',
    subCategory: 'Indian & Desi',
    gender: 'female',
    description: 'Palace courtyard portrait with hand-woven royal silk poshak, jadau jewelry, and ethereal royal radiance.',
    badge: '👑 Royal Princess',
    creditCost: 50,
    featured: true,
    sortPriority: 5,
    isActive: true,
    prompt: 'Grand Rajasthani royal princess portrait in heritage palace jharokha, pure silk embroidered poshak, antique kundan jewelry, soft palace golden light',
    beforeFile: 'src/assets/images/aditi_before_1790227539553.jpg',
    afterFile: 'src/assets/images/aditi_royal_after_1790227553057.jpg',
    likesCount: 52400,
    tags: ['royal', 'princess', 'rajputana', 'palace', 'heritage', 'girls'],
  },
  {
    id: 'santorini-greek-island',
    type: 'photo',
    name: 'Santorini Island Cliff',
    category: 'travel',
    subCategory: 'Lifestyle & Location',
    gender: 'female',
    description: 'Iconic white-washed Santorini cliffside with deep Aegean blue sea, azure domes, and radiant Mediterranean sun.',
    badge: '🇬🇷 Santorini',
    creditCost: 50,
    featured: false,
    sortPriority: 6,
    isActive: true,
    prompt: 'Pristine Santorini cliffside portrait, white Cycladic architecture, Aegean Sea horizon, elegant linen resort dress',
    beforeFile: 'src/assets/images/aditi_before_1790227539553.jpg',
    afterFile: 'src/assets/images/aditi_santorini_1790227566396.jpg',
    likesCount: 53400,
    tags: ['santorini', 'travel', 'vacation', 'location', 'greece'],
  },
  {
    id: 'haute-couture-vogue',
    type: 'photo',
    name: 'Haute Couture Vogue Cover',
    category: 'fashion',
    subCategory: 'Artistic & AI Transformation',
    gender: 'female',
    description: 'Front-cover editorial studio portrait with striking directional beauty dish lighting and emerald gown.',
    badge: 'Vogue Cover',
    creditCost: 50,
    featured: true,
    sortPriority: 7,
    isActive: true,
    prompt: 'Vogue magazine cover fashion editorial portrait, high contrast beauty dish studio lighting, designer emerald green gown',
    beforeFile: 'src/assets/images/aditi_before_1790227539553.jpg',
    afterFile: 'src/assets/images/aditi_vogue_1790227580130.jpg',
    likesCount: 47200,
    tags: ['vogue', 'editorial', 'haute couture', 'fashion', 'magazine'],
  },
  {
    id: 'paris-cafe-aesthetic',
    type: 'photo',
    name: 'Parisian Café Chic',
    category: 'social',
    subCategory: 'Lifestyle & Location',
    gender: 'female',
    description: 'Effortless Parisian sidewalk bistro marble table with warm morning latte and chic trench coat.',
    badge: '🥐 Paris Café',
    creditCost: 50,
    featured: false,
    sortPriority: 8,
    isActive: true,
    prompt: 'Effortless lifestyle portrait seated at vintage Parisian sidewalk cafe, soft morning dappled sunlight, stylish trench coat',
    beforeFile: 'src/assets/images/aditi_before_1790227539553.jpg',
    afterFile: 'src/assets/images/aditi_cafe_1790227595453.jpg',
    likesCount: 49800,
    tags: ['paris', 'cafe', 'lifestyle', 'travel', 'europe'],
  },
  {
    id: 'goa-beach-sunset',
    type: 'photo',
    name: 'Goa Beach Sunset',
    category: 'travel',
    subCategory: 'Lifestyle & Location',
    gender: 'female',
    description: 'Warm golden sunset on Goa beach, palm trees gently swaying, gentle ocean surf, and relaxed vacation style.',
    badge: '🏖️ Goa Beach',
    creditCost: 50,
    featured: true,
    sortPriority: 9,
    isActive: true,
    prompt: 'Standing on Goa beach during sunset, golden hour warm rim light, gentle ocean waves crashing, relaxed coastal vacation outfit',
    beforeFile: 'src/assets/images/aditi_before_1790227539553.jpg',
    afterFile: 'src/assets/images/aditi_beach_after_1790227622384.jpg',
    likesCount: 71200,
    tags: ['goa beach', 'beach', 'sunset', 'vacation', 'travel', 'location'],
  },
  {
    id: 'black-suit-gold-lighting',
    type: 'photo',
    name: 'Black Suit — Gold Lighting',
    category: 'royal',
    subCategory: 'Luxury & Rich Look',
    gender: 'male',
    description: 'Editorial black suit styling illuminated by warm honey-gold volumetric light with high-end supercar backdrop.',
    badge: '💎 Gold Light',
    creditCost: 50,
    featured: true,
    sortPriority: 10,
    isActive: true,
    prompt: 'High fashion editorial male portrait in bespoke black three-piece suit, amber gold rim lighting, exotic matte black supercar background, 85mm lens',
    beforeFile: 'src/assets/images/vikram_before_1790252169550.jpg',
    afterFile: 'src/assets/images/vikram_after_luxury_1790252183641.jpg',
    likesCount: 42100,
    tags: ['black suit', 'gold lighting', 'boys', 'luxury', 'supercar', 'men'],
  },
  {
    id: 'cyberpunk-future-city',
    type: 'photo',
    name: 'Cyber Future 2077',
    category: 'creative',
    subCategory: 'Artistic & AI Transformation',
    gender: 'male',
    description: 'Futuristic sci-fi mega-city with holographic billboards, neon rain reflections, and high-tech styling.',
    badge: '⚡ Cyberpunk',
    creditCost: 50,
    featured: false,
    sortPriority: 11,
    isActive: true,
    prompt: 'Futuristic cyberpunk neon metropolis portrait, holographic reflections, sleek high-tech jacket, cinematic blade runner aesthetic',
    beforeFile: 'src/assets/images/vikram_before_1790252169550.jpg',
    afterFile: 'src/assets/images/vikram_cyber_after_1790252198290.jpg',
    likesCount: 56700,
    tags: ['cyberpunk', 'futuristic', 'sci-fi', 'neon', 'artistic'],
  },
  {
    id: 'sabyasachi-palace-bride',
    type: 'photo',
    name: 'Royal Sabyasachi Palace Bride',
    category: 'wedding',
    subCategory: 'Wedding & Groom',
    gender: 'female',
    description: 'Majestic crimson red bridal lehenga with heavy antique gold zardozi embroidery and royal polki diamond choker.',
    badge: '👰 Royal Bride',
    creditCost: 50,
    featured: true,
    sortPriority: 12,
    isActive: true,
    prompt: 'Regal Indian bride portrait in grand palace courtyard, ruby red and antique gold zardozi embroidered lehenga, uncut diamond polki',
    beforeFile: 'src/assets/images/ananya_before_1790252210668.jpg',
    afterFile: 'src/assets/images/ananya_after_bridal_1790252223298.jpg',
    likesCount: 65100,
    tags: ['wedding', 'bride', 'lehenga', 'sabyasachi', 'royal'],
  },
  {
    id: 'golden-hour-cafe-profile',
    type: 'photo',
    name: 'Golden Hour Sunset Profile',
    category: 'social',
    subCategory: 'Social Media & Profile',
    gender: 'female',
    description: 'Glowing warm golden hour sunset light kissing hair and skin at a sunlit aesthetic cafe.',
    badge: '✨ Golden Hour',
    creditCost: 50,
    featured: false,
    sortPriority: 13,
    isActive: true,
    prompt: 'Sun-drenched golden hour rooftop cafe lifestyle portrait, warm backlit glow through hair, effortless ivory linen shirt',
    beforeFile: 'src/assets/images/ananya_before_1790252210668.jpg',
    afterFile: 'src/assets/images/ananya_after_insta_1790252236897.jpg',
    likesCount: 58900,
    tags: ['golden hour', 'instagram', 'profile', 'aesthetic', 'sunset'],
  },
  {
    id: 'urban-street-king',
    type: 'photo',
    name: 'Urban Street King',
    category: 'trending',
    subCategory: 'Streetwear',
    gender: 'male',
    description: 'Raw city street vibe with oversized streetwear, retro chunky sneakers, and confident urban king demeanor.',
    badge: '🔥 Street King',
    creditCost: 50,
    featured: false,
    sortPriority: 14,
    isActive: true,
    prompt: 'Urban street king portrait on Mumbai promenade, oversized streetwear jacket, vintage shades, golden hour bokeh',
    beforeFile: 'src/assets/images/kabir_before_1790252273376.jpg',
    afterFile: 'src/assets/images/kabir_after_viral_1790252286512.jpg',
    likesCount: 39100,
    tags: ['streetwear', 'street king', 'urban', 'boys', 'oversized'],
  },
  {
    id: 'cricket-matchday-portrait',
    type: 'photo',
    name: 'Cricket Matchday Portrait',
    category: 'fitness',
    subCategory: 'Sports & Motorsport',
    gender: 'male',
    description: 'Heroic cricket athlete portrait under floodlights with official jersey look and roaring stadium atmosphere.',
    badge: '🏏 Cricket Star',
    creditCost: 50,
    featured: true,
    sortPriority: 15,
    isActive: true,
    prompt: 'Indian cricket athlete hero portrait under bright stadium floodlights, national athletic jersey, mist and bokeh',
    beforeFile: 'src/assets/images/kabir_before_1790252273376.jpg',
    afterFile: 'src/assets/images/kabir_fitness_after_1790252301524.jpg',
    likesCount: 62800,
    tags: ['cricket', 'sports', 'matchday', 'athlete', 'stadium', 'boys'],
  },
  {
    id: 'temple-kanjeevaram-heritage',
    type: 'photo',
    name: 'Temple Kanjeevaram Heritage',
    category: 'royal',
    subCategory: 'Indian & Desi',
    gender: 'female',
    description: 'Pure woven gold zari Kanjeevaram silk saree with ancient temple pillars and warm ceremonial diya bokeh.',
    badge: '🪔 Temple Heritage',
    creditCost: 50,
    featured: false,
    sortPriority: 16,
    isActive: true,
    prompt: 'Grand temple corridor portrait, pure mulberry silk Kanjeevaram saree with rich gold zari border, antique temple jewelry',
    beforeFile: 'src/assets/images/meera_before_1790252314279.jpg',
    afterFile: 'src/assets/images/meera_temple_after_1790252326870.jpg',
    likesCount: 48300,
    tags: ['temple', 'kanjeevaram', 'saree', 'desi', 'heritage'],
  },
  {
    id: 'old-money-classic',
    type: 'photo',
    name: 'Old-Money Classic',
    category: 'fashion',
    subCategory: 'Luxury & Rich Look',
    gender: 'female',
    description: 'Timeless quiet luxury aesthetic featuring cream cashmere knit, vintage polo club lawn, and aristocratic poise.',
    badge: 'Old Money',
    creditCost: 50,
    featured: false,
    sortPriority: 17,
    isActive: true,
    prompt: 'Old-money quiet luxury female aesthetic portrait, cream cashmere sweater, heritage country club estate, soft afternoon natural light',
    beforeFile: 'src/assets/images/meera_before_1790252314279.jpg',
    afterFile: 'src/assets/images/meera_oldmoney_after_1790252340767.jpg',
    likesCount: 41800,
    tags: ['old money', 'classic', 'luxury', 'girls', 'quiet luxury'],
  },
];

const videoTemplates = [
  {
    id: 'face-swap-bollywood-star',
    type: 'video',
    name: 'Bollywood Star Face-Swap Video',
    category: 'face_swap',
    subCategory: 'Face Swap Video (Photo to Video)',
    description: 'Swap your normal facial photo into a high-octane Bollywood cinematic slow-motion video. Seamless neural face blending.',
    badge: '🎭 Viral Face Swap',
    creditCost: 150,
    featured: true,
    sortPriority: 1,
    isActive: true,
    prompt: 'High fidelity face swap into royal Bollywood wedding hero entry video, cinematic slow motion, golden firework bokeh',
    coverFile: 'src/assets/images/aarav_royal_after_1790227528118.jpg',
    faceFile: 'src/assets/images/aarav_before_1790227490151.jpg',
    targetVideoFrameFile: 'src/assets/images/aarav_royal_after_1790227528118.jpg',
    previewVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-fashion-model-in-neon-lights-39878-large.mp4',
    likesCount: 88400,
    tags: ['face swap', 'bollywood', 'video', 'photo to video', 'slow motion'],
  },
  {
    id: 'image-to-cinematic-movie',
    type: 'video',
    name: 'Image to Cinematic Movie Trailer',
    category: 'image_to_video',
    subCategory: 'Image to Video Motion',
    description: 'Turn any static Indian portrait into a Hollywood & Bollywood level cinematic camera push-in movie scene.',
    badge: '🎬 Movie Magic',
    creditCost: 120,
    featured: true,
    sortPriority: 2,
    isActive: true,
    prompt: 'Cinematic slow zoom camera push-in, natural facial expressions, subtle blinking, atmospheric haze and warm anamorphic flare',
    coverFile: 'src/assets/images/hero_glamour_woman_1790349658022.jpg',
    previewVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-girl-walking-on-the-beach-at-sunset-1250-large.mp4',
    likesCount: 76200,
    tags: ['image to video', 'cinematic', 'movie', 'motion', 'animation'],
  },
  {
    id: 'supercar-neon-night-drive',
    type: 'video',
    name: 'Supercar Neon Midnight Chase',
    category: 'video_to_video',
    subCategory: 'Video-to-Video Restyling',
    description: 'Transform regular street driving footage into a fast & furious neon cyber chase with ultra-glossy lighting reflections.',
    badge: '🏎️ Neon Chase',
    creditCost: 140,
    featured: true,
    sortPriority: 3,
    isActive: true,
    prompt: 'Midnight Dubai neon highway supercar chase, wet asphalt neon reflections, dynamic motion blur, 4K cinematic 60fps',
    coverFile: 'src/assets/images/neon_supercar_night_1790349710444.jpg',
    previewVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-traffic-at-night-in-a-big-city-4315-large.mp4',
    likesCount: 64900,
    tags: ['supercar', 'video to video', 'neon', 'night drive', 'chase'],
  },
  {
    id: 'royal-palace-heritage-drone',
    type: 'video',
    name: 'Royal Palace Heritage Orbit',
    category: 'text_to_video',
    subCategory: 'Text-to-Video Motion',
    description: 'Breathtaking 360-degree drone orbit around a grand Rajasthani illuminated heritage palace at twilight.',
    badge: '👑 Royal Drone',
    creditCost: 110,
    featured: false,
    sortPriority: 4,
    isActive: true,
    prompt: 'Smooth 360 drone orbit around illuminated Udaipur Lake Palace at twilight, reflected water ripples, royal festive torches',
    coverFile: 'src/assets/images/golden_palace_night_1790349693531.jpg',
    previewVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-aerial-view-of-a-luxurious-hotel-at-sunset-41481-large.mp4',
    likesCount: 52100,
    tags: ['palace', 'drone', 'heritage', 'text to video', 'rajasthan'],
  },
  {
    id: 'party-glamour-slowmo',
    type: 'video',
    name: 'Party Glamour VIP Slow-Mo',
    category: 'image_to_video',
    subCategory: 'Image to Video Motion',
    description: 'Bring any glamorous party photo to life with slow-motion champagne toast, glittering lights, and joyful smiles.',
    badge: '✨ VIP Party',
    creditCost: 120,
    featured: false,
    sortPriority: 5,
    isActive: true,
    prompt: 'Ultra-luxurious VIP lounge party, slow-motion golden confetti falling, soft bokeh lights, stylish toast',
    coverFile: 'src/assets/images/glamour_girl_chat_1790349675295.jpg',
    previewVideoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-hands-holding-champagne-glasses-and-toasting-at-a-party-41712-large.mp4',
    likesCount: 48700,
    tags: ['party', 'image to video', 'slow motion', 'vip', 'champagne'],
  },
];

// Helper to create and copy files
const baseDir = path.resolve(process.cwd(), 'template-library');
const photoBase = path.join(baseDir, 'photo');
const videoBase = path.join(baseDir, 'video');

fs.mkdirSync(photoBase, { recursive: true });
fs.mkdirSync(videoBase, { recursive: true });

// Process Photo Templates
for (const pt of photoTemplates) {
  const dir = path.join(photoBase, pt.id);
  fs.mkdirSync(dir, { recursive: true });

  const beforeSrc = path.resolve(process.cwd(), pt.beforeFile);
  const afterSrc = path.resolve(process.cwd(), pt.afterFile);

  const beforeDest = path.join(dir, 'before.jpg');
  const afterDest = path.join(dir, 'after.jpg');
  const previewDest = path.join(dir, 'preview.jpg');

  if (fs.existsSync(beforeSrc)) fs.copyFileSync(beforeSrc, beforeDest);
  if (fs.existsSync(afterSrc)) {
    fs.copyFileSync(afterSrc, afterDest);
    fs.copyFileSync(afterSrc, previewDest);
  }

  const meta = {
    id: pt.id,
    type: 'photo',
    name: pt.name,
    category: pt.category,
    subCategory: pt.subCategory,
    gender: pt.gender,
    description: pt.description,
    badge: pt.badge,
    previewPath: `/template-library/photo/${pt.id}/preview.jpg`,
    beforePath: `/template-library/photo/${pt.id}/before.jpg`,
    afterPath: `/template-library/photo/${pt.id}/after.jpg`,
    prompt: pt.prompt,
    creditCost: pt.creditCost,
    featured: pt.featured,
    sortPriority: pt.sortPriority,
    isActive: pt.isActive,
    likesCount: pt.likesCount,
    tags: pt.tags,
  };

  fs.writeFileSync(path.join(dir, 'template.json'), JSON.stringify(meta, null, 2), 'utf-8');
}

// Process Video Templates
for (const vt of videoTemplates) {
  const dir = path.join(videoBase, vt.id);
  fs.mkdirSync(dir, { recursive: true });

  const coverSrc = path.resolve(process.cwd(), vt.coverFile);
  const coverDest = path.join(dir, 'cover.jpg');
  const previewDest = path.join(dir, 'preview.jpg');

  if (fs.existsSync(coverSrc)) {
    fs.copyFileSync(coverSrc, coverDest);
    fs.copyFileSync(coverSrc, previewDest);
  }

  if (vt.faceFile) {
    const faceSrc = path.resolve(process.cwd(), vt.faceFile);
    if (fs.existsSync(faceSrc)) fs.copyFileSync(faceSrc, path.join(dir, 'face.jpg'));
  }

  const meta = {
    id: vt.id,
    type: 'video',
    name: ptOrVtName(vt.name),
    category: vt.category,
    subCategory: vt.subCategory,
    description: vt.description,
    badge: vt.badge,
    previewPath: `/template-library/video/${vt.id}/cover.jpg`,
    coverPath: `/template-library/video/${vt.id}/cover.jpg`,
    videoPath: vt.previewVideoUrl,
    prompt: vt.prompt,
    creditCost: vt.creditCost,
    featured: vt.featured,
    sortPriority: vt.sortPriority,
    isActive: vt.isActive,
    likesCount: vt.likesCount,
    tags: vt.tags,
  };

  fs.writeFileSync(path.join(dir, 'template.json'), JSON.stringify(meta, null, 2), 'utf-8');
}

function ptOrVtName(name: string) {
  return name;
}

console.log('✅ Template Library population complete!');
